#!/usr/bin/env ruby
#"git://github.com/ervandew/supertab.git",
git_bundles = [
  "git://github.com/bling/vim-airline.git",
  "git://github.com/nvie/vim-pyunit.git",
  "git://github.com/klen/python-mode.git",
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/depuracao/vim-rdoc.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tsaleh/vim-tmux.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/vim-scripts/Gist.vim.git",
  "git://github.com/scrooloose/syntastic",
  "git://github.com/rodjek/vim-puppet.git",
  "git://github.com/vim-scripts/Specky.git",
  "git://github.com/markcornick/vim-vagrant.git",
  "git://github.com/marcweber/vim-addon-mw-utils",
  "git://github.com/tomtom/tlib_vim",
  "git://github.com/vadv/vim-chef"
]

git_custom = {
  "https://github.com/egeland/puppet.snippets/blob/master/puppet.snippets" => "snipmate.vim/snippets/puppet.snippets"
}

vim_org_scripts = [
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils::mkdir_p(bundles_dir)
FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

git_custom.each do |url, dest|
  puts "checking out custom file into #{dest}"
  `curl -o #{dest} #{url}`
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
